- Project.toml
- docs/src/models.md
- src/SpectralFitting.jl
- src/ccall-wrapper.jl
- src/file-io/model-data-io.jl
- src/julia-models/additive.jl
- src/surrogate-models.jl
- src/xspec-models/additive.jl
- src/xspec-models/multiplicative.jl
Changes to [LibXSPEC_jll](https://github.com/astro-group-bristol/LibXSPEC_jll.jl) now ship light-weight artifacts with all of the bloated model data removed, and fixes issues with undefined symbols in libgfortran.
- These commits add a data fetcher which downloads the requisite model data from the Bristol astro servers.
- Also update documentation for the now fixed models.
> Model data fetching

- src/plotting-recipes.jl
- src/poisson.jl
- src/spectral-datasets/binning-utilities.jl
- src/spectral-datasets/dataset-types.jl
- src/spectral-datasets/datasets.jl
- src/spectral-datasets/missions/no-associated-mission.jl
- src/spectral-datasets/missions/xmm-newton-mission.jl
- src/spectral-datasets/ogip-io.jl
- src/spectral-datasets/response-matrix.jl
Removing some of the association that the bins are always energy (allow for frequency fits too without that weird double think).
Also cleaned up the OGIP parsing a little by separating headers, in preparation for a direct source/background parser. Renamed to `GroupedEvents` for now. Need method for calculating area and background scaling factor in the package directly, since this is currently done by `grppha`.
> Rename functions and fields

- Project.toml
- src/ccall-wrapper.jl
Previously all models had to be defined as symbols in the `libXSFunctions` shared library. Now, the `@xspecmodel` macro may accept a tuple in place of a symbol, where the second argument to the tupple specifies the callsite of the function.
> ccall: allow callsite specification

- src/xspec-models/additive.jl
Minor changes:
- `incl` changed to `\theta`
- `\theta` restricted to 0 to 90 degrees
- `\theta` a free parameter by default
> Updated XS_KerrDisk model

- src/julia-models/multiplicative.jl
A very simple fix to switch to the newer Interpolations.jl constructor.
While deprecated functions can cause performance penalties that doesn't appear to be the case here so the primary advantage is suppressing the warning message.
> Replace deprecated LinearInterpolation

- src/datasets/injectivedata.jl
- test/fitting/test-fit-simple-dataset.jl
This pull request adds a new field `data_mask` to the `InjectiveData` struct. The `data_mask` is a `BitVector` that allows for masking specific data points in the `codomain` array. This feature is useful for filtering out certain data points during analysis or modeling. The `data_mask` is initialized with all `true` values by default.
> Add data_mask to InjectiveData

- src/xspec-models/additive.jl
Added the interface to `XS_Jet`, the `jet` model in XSPEC. Just realised I forgot the nice ASCII art overview plot to go with the model.
> Add XS_Jet model to xspec-models

- .github/workflows/test.yml
- src/abstract-models.jl
- src/fitting/cache.jl
Closes #79 
Bumping CI version here as it failed to catch the issue.
> Fix `mul!` problems and bump Julia CI version

- src/print-utilities.jl
Perhaps a bit clunky but a quick, simple fix so `prettyfloat` function works around `InexactError` if it crops up. I couldn't quickly think of a way of doing this more compactly without adding $\sim 9$ lines of code!
We ran into the `InexactError` because we were using frequency units rather than keV so some numbers became extremely large (e.g., 6.579332246575656e24).
> Temporary fix to `prettyfloat` to work around `InexactError`

- src/xspec-models/additive.jl
Added cut-off power law model from XSPEC. The `zcutoffpl` model is now available as `XS_CutOffPowerLaw`.
> Cut-off power law model from XSPEC

- src/fitting/binding.jl
- test/fitting/test-binding.jl
This PR addresses #89 regarding a problem with `bind` if there are multiple models and datasets.
Once a parameter has been bound to another parameter it must relinquish the parameter number it had before being bound. This means that there is now a gap in the contiguous list of parameter numbers. Larger parameter numbers then need to be shuffled down by one to fill this gap, resulting in a contiguous list of parameters. The problem was that all later parameters in the lit were being decremented by 1 regardless of whether they were larger or not.
A test case has been added to check that `bind` works as anticipated for multiple models and datasets. Further tests could usefully be added.
Finally, there are lots of debugging `println` statements that can be removed once we're satisfied the …
> Fixing bind mapping with multiple models

- .github/workflows/docs.yml
- docs/src/walkthrough.md
- src/fitparam.jl
- src/fitting/config.jl
- src/fitting/methods.jl
- src/fitting/result.jl
Closes #106 kind of. We just help the compiler so our parts of the code are type stable, but it seems to be an ongoing issue being tracked in Optimizations.jl, see https://github.com/SciML/Optimization.jl/issues/556.
> Add MCMC docs and result type stability

- src/datasets/spectraldata.jl
- src/plots-recipes.jl
This is a draft PR for plotting unfolded data and model (see #82). This draft will use the XSPEC method of calculation. It is a WIP and *not* ready to be merged. There are a couple of things I don't know how to do, and perhaps a bug I need to chase down.
> Plot unfolded data and model

- src/SpectralFitting.jl
- src/abstract-models.jl
- src/meta-models/caching.jl
- src/meta-models/wrappers.jl
- src/reflection.jl
- test/models/test-auto-cache.jl
- test/runtests.jl
Added a new abstract type for creating model wrappers. These are models which wrap other models without introducing new parameters, but can change the way the underlying model is used.
One example of this is included: `AutoCache`, which caches the last output of the model and returns the cached output if the parameters have all changed by less than some absolute tolerance. This can save the number of calls to expensive models where the parameter space is not changing by much, and speedup fits.
> feat: model wrappers and AutoCache

- src/fitting/binding.jl
- test/fitting/test-binding.jl
When binding parameters we should only be considering free parameters in the model, not all parameters. Updated _get_index_of_symbol in binding.jl to skip frozen parameters.
Added a couple of test cases to check this works. Could probably add more tests.
> fix: bind parameters in models with frozen parameters

- src/xspec-models/additive.jl
Adding a draft for the Optxagnf model. Not yet tested if it is working.
> Adding Optxagnf model

- src/xspec-models/convolutional.jl
Adding a new convolutional model XS_Kerrconv
> Add XS_Kerrconv model to convolutional.jl

- Project.toml
- docs/src/models/models.md
- src/SpectralFitting.jl
- src/julia-models/additive.jl
- test/models/test-julia-models.jl
> BremsStrahlung Julia implementation

- src/meta-models/table-models.jl
Fixing the issue of reversed data in the interpolation of table models. The fix involved reversing the order of the parameter_axes and then reversing the order of the variables in the table invocation. This is not the most elegant way of doing this but it works. 
Varying logxi before the fix 
Varying logxi after the fix
> fixed the issues with reversed data when interpolating

- lib/XSPECModels/src/additive.jl
Fixed a couple of trivial typos. Also changed parameter descrition of XS_Gaussian to be in energy / keV.
> fix: typos and XS_Gaussian wavelength -> energy in text label

- src/SpectralFitting.jl
- src/meta-models/parameter-patch.jl
- test/models/test-patching.jl
- test/runtests.jl
@DariusMichienzi here's the parameter patching. An example:
```julia
model = PowerLaw() + PowerLaw()
function patcher!(p)
p.a1.K = p.a2.K / 2
p.a1.a = sqrt(p.a2.a) + sin(p.a1.a)
end
patched_model = ParameterPatch(model; patch = patcher!)
patched_model.a1.K.frozen = true
patched_model.a1.a.frozen = true
```
In the future I'll make it do that freezing automatically.
That's all you need to do. Then use `patched_model` as before!
I haven't programmed the user-interface bits yet, so that or how things are being patched is a little opaque at the moment, but I have added an `apply_patch!` function that you can give a `ParameterPatch` model to. This function will apply whatever your patch function does to your `FitParam` model. In practice, you'd want to do
```julia
result = fit(prob, …
```
> feat: add ParameterPatch
