- src/abstract-models.jl
- src/model-processing.jl
Adds a function which builds an anonymous function that is compatible with LsqFit.jl from a processed model.
Some notes:
- need a good way of holding on to lower and upper bounds on models
- might be useful to add a `ModelParameter` struct which can track different things related to parameters, e.g. ranges, frozen state, priors.
> Least Squares Model

- src/SpectralFitting.jl
- src/abstract-models.jl
- src/energy-and-response.jl
- src/file-io.jl
- src/fit-parameters.jl
- src/model-building.jl
- src/model-processing.jl
- src/xspec-models/additive.jl
Redesigned and refined how the model building works to keep hold of three in-place flux arrays, and juggle their use in complex models to minimize allocations.
> Model building

- Project.toml
- src/SpectralFitting.jl
- src/fitting.jl
- src/model-building.jl
- src/parameters.jl
Also added automated least-squares parameter fitting and fix world-age error.
> MCMC model builder

- Project.toml
- src/SpectralFitting.jl
- src/abstract-models.jl
- src/datasets.jl
- src/file-io.jl
- src/fitting.jl
- src/model-building.jl
- src/model-processing.jl
- src/parameters.jl
- src/plotting-recipes.jl
Recipes only for Makie at the moment. Also added standard deviation fit parameter type.
> Datasets and plot recipes

- src/SpectralFitting.jl
- src/abstract-models.jl
- src/composite-models.jl
- src/energy-and-response.jl
- src/fitparam.jl
- src/fitting.jl
- src/julia-models/additive.jl
- src/model-building.jl
- src/model-processing.jl
- src/surrogate-models.jl
Fixed bugs in how model building constructs `M * M * A` or `M * M * A + M * A` to avoid flux counts exceeding 3.
> Model building fixes

- README.md
- docs/make.jl
- docs/src/composite-models.md
- docs/src/models.md
- docs/src/reference.md
- docs/src/surrogate-models.md
- docs/src/using-models.md
- src/abstract-models.jl
- src/ccall-wrapper.jl
- src/composite-models.jl
- src/file-io/binning-utilities.jl
- src/fitparam.jl
- src/function-generation.jl
- src/julia-models/additive.jl
- src/julia-models/model-utilities.jl
- src/parsing-utilities.jl
- src/surrogate-models.jl
- src/xspec-models/additive.jl
- src/xspec-models/multiplicative.jl
Added unicode fingerprint plots for each of the spectral models. Also added lots more documentation and bugfixes.
> Docs fingerprint plots

- docs/src/models.md
- docs/src/why-and-how.md
Documentation about how models are used to create efficient Julia functions.
> Source-rewriting docs

- Project.toml
- src/abstract-models.jl
- src/composite-models.jl
- src/fitparam.jl
- src/fitting.jl
- src/generation/function-generation.jl
- src/generation/wrappers.jl
- test/generation/test-introspection.jl
- test/generation/test-parsing-utilities.jl
- test/io/test-printing.jl
- test/models/test-julia-models.jl
- test/parameters/test-model-parameters.jl
- test/runtests.jl
With the coverage report from #30 I have been able to start treeshaking unused functions from the code base, and generally cleaning up the interface.
Added a variety more tests for things related to parameters and parameter accesses.
> Parameters: started rework and treeshaking

- Project.toml
- src/datasets/spectral-datasets.jl
- src/fitting/methods.jl
- src/fitting/problem.jl
- test/fitting/test-sample-data.jl
> Feat: background subtraction

- .gitignore
- Project.toml
- src/datasets/simple-dataset.jl
- Added placeholders for simple-dataset background subtraction.
- Incremented version number.
I have not used any parametric types in these definitions. This might not be good practice...
> Placeholders for simple-dataset background subtraction

- src/datasets/datasets.jl
- src/datasets/response.jl
- src/datasets/spectraldata.jl
- src/datasets/spectrum.jl
- src/fitting/problem.jl
- src/fitting/result.jl
- src/plotting-recipes.jl
- test/fitting/test-sample-data.jl
Closes #64 
Introduces a few new bugs in trying to fit the sample XMM data. Results are no longer consistent with XSPEC, and I believe this is because the variance vector that we calculate is incorrect.
> fix: response folding issues and uncertainties

- src/datasets/spectrum.jl
- src/plotting-recipes.jl
As noted in #91 the variance calculations were off for datasets without Poisson errors. This PR fixes that.
> Fix variance calculations

- src/fitting/binding.jl
- src/plotting-recipes.jl
- src/print-utilities.jl
- src/xspec-models/additive.jl
- test/fitting/test-binding.jl
Draft plotting recipe for residual plots. Needs some updating to make the plots better, and to allow more user-defined options.
> Residual plots

- Project.toml
- src/xspec-models/additive.jl
Fixed a typo in the XSPEC model cut off power law doc string
> Fixed a typo and bumped version

- .github/workflows/docs.yml
- docs/make.jl
- docs/src/walkthrough.md
Let's see how many tries it takes to get the CI working...
> Docs and walkthrough

- src/composite-models.jl
- src/fitting/binding.jl
- src/fitting/cache.jl
- src/fitting/problem.jl
- test/fitting/test-binding.jl
- test/io/test-printing.jl
> Fix parameter bindings

- Project.toml
- src/SpectralFitting.jl
- src/fitting/problem.jl
- src/julia-models/additive.jl
- src/meta-models/surrogate-models.jl
- src/meta-models/table-models.jl
- src/model-data-io.jl
- test/models/test-xspec-models.jl
- test/runtests.jl
Still todo
```julia
using SpectralFitting
FITS_PATH = "/data/astro/model-data/xillverD-5.fits"
interp = TableModelInterpolation(TableModelData(Val(5), FITS_PATH ; T = Float32))
flux = SpectralFitting.interpolate_table!(interp,
1.5, 0.7, 0.2, 16.1, 66.0
)
energy = interp.data.energy_bins
```
This should provide all the functionality needed to wrap new models.
> Table Models

- docs/src/datasets/datasets.md
- docs/src/examples/sherpa-example.md
- docs/src/models/using-models.md
- lib/XSPECModels/src/ccall-wrapper.jl
- lib/XSPECModels/test/test-sample-data.jl
- lib/XSPECModels/test/test-validity.jl
- src/abstract-models.jl
- src/composite-models.jl
- src/datasets/binneddata.jl
- src/datasets/binning.jl
- src/datasets/datasets.jl
- src/datasets/injectivedata.jl
- src/datasets/spectraldata.jl
- src/fitting/config.jl
- src/fitting/problem.jl
- src/fitting/result.jl
- src/meta-models/caching.jl
- src/meta-models/functions.jl
- src/meta-models/surrogate-models.jl
- src/meta-models/wrappers.jl
- src/param-cache.jl
- src/support.jl
- test/fitting/test-cache.jl
- test/models/test-as-convolution.jl
- test/models/test-model-api.jl
- test/models/test-table-models.jl
- test/runtests.jl
Commit messages have the details.
> Refactor invoke and wrapper interface

- src/simulate.jl
- test/simulation/test-sample-data-sim.jl
- test/simulation/test-simulation.jl
> Fix simulation API

- src/fitting/config.jl
- src/fitting/problem.jl
- test/fitting/test-domain-extension.jl
- test/runtests.jl
No API yet, but the core logic.
> Domain extensions
